const {chromium}=require('playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync(__dirname+'/../index.html','utf8');
 const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).filter(x=>x.includes('let appState'));
 await page.setContent(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,''));
 await page.addStyleTag({content:'.hidden{display:none!important} [class*="absolute"]{position:absolute} [class*="inset-0"]{inset:0} #account-modal{z-index:85} #recurring-expense-modal{z-index:86} #recurring-date-picker-modal{z-index:88}'});
 await page.evaluate(()=>window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>{}},functions:{invoke:async()=>({data:{configured:false}})}})});
 await page.addScriptTag({content:scripts[0]});
 const results=await page.evaluate(()=>{
  const close=(a,b)=>Math.abs(a-b)<0.001;
  appState.taxProfile=null;
  const low=calculateTaxEstimate(4121-1037);
  if(low.total!==0)throw new Error('£3,084 profit must have zero tax');
  const standard=calculateTaxEstimate(30000);
  if(!close(standard.incomeTax,3486)||!close(standard.class4,1045.8))throw new Error('Standard tax bands failed');
  const high=calculateTaxEstimate(125140);
  if(!close(high.incomeTax,42516))throw new Error('Tapered allowance/higher band failed');
  appState.taxProfile={tax_residence:'Scotland',marriage_allowance:'receiving'};
  const marriage=calculateTaxEstimate(30000);
  appState.taxProfile={tax_residence:'Scotland'};
  const without=calculateTaxEstimate(30000);
  if(!close(without.incomeTax-marriage.incomeTax,252))throw new Error('Marriage credit failed');
  appState.taxProfile=null;
  appState.recurringExpenses=[{id:'cost',is_active:false,start_date:'2026-03-28',end_date:'2026-03-30',amount:365.2425,frequency:'yearly',category:'Insurance'}];
  const past=getRecurringCostShare('2026-03-28','2026-03-30').total;
  const future=getRecurringCostShare('2026-03-31','2026-04-02').total;
  if(!close(past,3)||future!==0)throw new Error('Stopped cost history / DST failed');
  appState.recurringExpenses=[];
  appState.transactions=[{id:'inc',type:'income',date:'2026-04-06',amount:4121,source:'Uber'},{id:'exp',type:'expense',date:'2026-04-06',amount:1037,category:'Fuel'}];
  if(getTaxYearSummary().total!==0 || getEstimatedDailyTaxReserve('2026-04-06')!==0)throw new Error('Tax summary/range regression');
  appState.taxProfile={paye_income:30000};
  appState.transactions=[];
  if(getEstimatedDailyTaxReserve('2026-04-06')!==0)throw new Error('Other income incorrectly charged on first day');
  appState.taxProfile=null;
  appState.profile={full_name:'Driver',primary_work_type:'Taxi / Private Hire',platforms:['Uber'],usual_expenses:['Fuel']};
  appState.currentUser={id:'test',email:'test@example.com'};
  document.getElementById('auth-screen').classList.add('hidden');
  document.getElementById('onboarding-screen').classList.add('hidden');
  openAccountModal();openRecurringExpenseModal();
  if(Number(getComputedStyle(document.getElementById('recurring-expense-modal')).zIndex)<=Number(getComputedStyle(document.getElementById('account-modal')).zIndex))throw new Error('Regular cost dialog behind profile');
  closeRecurringExpenseModal();
  appState.selectedPlatforms.push('Unsaved');closeAccountModal();
  if(appState.selectedPlatforms.includes('Unsaved'))throw new Error('Cancelled profile edits leaked');
  const name='A "quote" <tag> O\'Brien';
  document.getElementById('profile-platform-chips').innerHTML=chipButton(name,false,'toggleProfilePlatform');
  document.getElementById('profile-platform-chips').firstChild.click();
  if(!appState.selectedPlatforms.includes(name))throw new Error('Custom platform escaping failed');
  switchTab('records');openCalendarTab();closeCalendarModal();
  if(!document.getElementById('nav-dashboard').classList.contains('text-emerald-400'))throw new Error('Calendar return navigation failed');
  if(document.getElementById('vehicle-make'))throw new Error('Vehicle section still present');
  return {lowProfitTax:low.total,standardTax:standard.total,highIncomeTax:high.incomeTax,pastCost:past,futureCost:future};
 });
 assert.deepEqual(errors,[]);console.log('PASS tax, stopped-cost history, DST, profile, modal, navigation and custom-label checks',results);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
